In [34]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [35]:
data =  []
df = pd.read_csv('./data_10.csv')
pos = df['Station_Name'].drop_duplicates().tolist()
for ind,i in enumerate(pos):
    ori = df[df['Station_Name'] == i].to_numpy()
    if ori.shape[0] != 744:
        continue
    data.append(ori)
np.save('./data_10.npy',data)
data

[array([['河口', 56989, 22.5, ..., 346, 0.6, 26.2],
        ['河口', 56989, 22.5, ..., 152, 0.7, 26.4],
        ['河口', 56989, 22.5, ..., 6, 0.4, 27.0],
        ...,
        ['河口', 56989, 22.5, ..., 0, 0.0, 22.4],
        ['河口', 56989, 22.5, ..., 0, 0.0, 22.3],
        ['河口', 56989, 22.5, ..., 0, 0.0, 22.1]], dtype=object),
 array([['万盛', 57509, 28.9894, ..., 37, 1.3, 18.7],
        ['万盛', 57509, 28.9894, ..., 8, 2.0, 19.7],
        ['万盛', 57509, 28.9894, ..., 20, 2.2, 20.1],
        ...,
        ['万盛', 57509, 28.9894, ..., 23, 1.0, 14.7],
        ['万盛', 57509, 28.9894, ..., 93, 0.4, 14.7],
        ['万盛', 57509, 28.9894, ..., 357, 1.1, 14.5]], dtype=object),
 array([['长寿', 57520, 29.8333, ..., 14, 2.1, 21.1],
        ['长寿', 57520, 29.8333, ..., 360, 2.3, 21.7],
        ['长寿', 57520, 29.8333, ..., 354, 0.8, 22.1],
        ...,
        ['长寿', 57520, 29.8333, ..., 233, 2.8, 15.5],
        ['长寿', 57520, 29.8333, ..., 259, 2.1, 15.4],
        ['长寿', 57520, 29.8333, ..., 236, 2.9, 15.4]], dtype=object),
 array([['黔江', 57536, 29.5167, ..., 53, 2.5, 17.3],
        ['黔江', 57536, 29.5167, ..., 62, 0.9, 19.6],
        ['黔江', 57536, 29.5167, ..., 53, 1.5, 22.0],
        ...,
        ['黔江', 57536, 29.5167, ..., 45, 1.1, 12.8],
        ['黔江', 57536, 29.5167, ..., 59, 0.9, 12.7],
        ['黔江', 57536, 29.5167, ..., 65, 1.9, 12.6]], dtype=object),
 array([['咸丰', 57540, 29.6844, ..., 79, 0.9, 17.3],
        ['咸丰', 57540, 29.6844, ..., 45, 1.5, 18.1],
        ['咸丰', 57540, 29.6844, ..., 39, 1.6, 19.0],
        ...,
        ['咸丰', 57540, 29.6844, ..., 65, 1.1, 12.2],
        ['咸丰', 57540, 29.6844, ..., 76, 0.9, 12.2],
        ['咸丰', 57540, 29.6844, ..., 56, 0.7, 12.2]], dtype=object),
 array([['宣恩', 57541, 29.9986, ..., 62, 1.2, 18.5],
        ['宣恩', 57541, 29.9986, ..., 169, 0.7, 21.3],
        ['宣恩', 57541, 29.9986, ..., 211, 0.8, 22.9],
        ...,
        ['宣恩', 57541, 29.9986, ..., 0, 0.0, 13.7],
        ['宣恩', 57541, 29.9986, ..., 98, 0.3, 13.5],
        ['宣恩', 57541, 29.9986, ..., 253, 0.6, 13.6]], dtype=object),
 array([['鹤峰', 57543, 29.8839, ..., 0, 0.2, 18.8],
        ['鹤峰', 57543, 29.8839, ..., 174, 1.0, 19.9],
        ['鹤峰', 57543, 29.8839, ..., 248, 0.5, 21.4],
        ...,
        ['鹤峰', 57543, 29.8839, ..., 0, 0.0, 13.9],
        ['鹤峰', 57543, 29.8839, ..., 0, 0.0, 14.0],
        ['鹤峰', 57543, 29.8839, ..., 0, 0.0, 13.9]], dtype=object),
 array([['田东', 59224, 23.6, ..., 249, 0.9, 24.2],
        ['田东', 59224, 23.6, ..., 108, 0.5, 25.5],
        ['田东', 59224, 23.6, ..., 96, 0.9, 27.8],
        ...,
        ['田东', 59224, 23.6, ..., 113, 2.2, 20.8],
        ['田东', 59224, 23.6, ..., 94, 2.3, 20.8],
        ['田东', 59224, 23.6, ..., 99, 1.2, 20.8]], dtype=object),
 array([['凭祥', 59419, 22.0667, ..., 128, 0.5, 23.4],
        ['凭祥', 59419, 22.0667, ..., 32, 0.4, 24.2],
        ['凭祥', 59419, 22.0667, ..., 134, 0.9, 27.7],
        ...,
        ['凭祥', 59419, 22.0667, ..., 138, 1.0, 18.7],
        ['凭祥', 59419, 22.0667, ..., 163, 0.4, 18.8],
        ['凭祥', 59419, 22.0667, ..., 123, 0.6, 17.9]], dtype=object),
 array([['宁明', 59427, 22.1167, ..., 62, 3.2, 24.5],
        ['宁明', 59427, 22.1167, ..., 54, 2.0, 25.7],
        ['宁明', 59427, 22.1167, ..., 77, 4.0, 26.9],
        ...,
        ['宁明', 59427, 22.1167, ..., 292, 0.9, 20.1],
        ['宁明', 59427, 22.1167, ..., 289, 1.5, 19.5],
        ['宁明', 59427, 22.1167, ..., 224, 0.7, 19.6]], dtype=object),
 array([['上思', 59429, 22.1833, ..., 59, 1.4, 24.5],
        ['上思', 59429, 22.1833, ..., 53, 2.2, 25.2],
        ['上思', 59429, 22.1833, ..., 98, 2.8, 27.7],
        ...,
        ['上思', 59429, 22.1833, ..., 253, 1.3, 20.4],
        ['上思', 59429, 22.1833, ..., 270, 0.9, 20.5],
        ['上思', 59429, 22.1833, ..., 262, 0.7, 20.5]], dtype=object),
 array([['东兴', 59626, 21.5667, ..., 352, 1.4, 28.5],
        ['东兴', 59626, 21.5667, ..., 25, 3.7, 32.1],
        ['东兴', 59626, 21.5667, ..., 73, 7.8, 36.7],
        ...,
        ['东兴', 59626, 21.5667, ..., 335, 4.1, 21.2],
        ['东兴', 59626, 21.5667, ..., 343, 2.6, 21.2],
        ['东兴', 59626, 21.5667, ..., 329, 3.8, 21.3]], dtype=object),
 array([['防城', 59631, 21.7833, ..., 360, 3.0, 25.5],
        ['防城', 59631, 21.7833, ..., 26, 4.6, 27.5],
        ['防城', 59631, 21.7833, ..., 17, 5.6, 27.8],
        ...,
        ['防城', 59631, 21.7833, ..., 14, 1.1, 22.0],
        ['防城', 59631, 21.7833, ..., 11, 1.3, 22.1],
        ['防城', 59631, 21.7833, ..., 20, 1.2, 22.0]], dtype=object),
 array([['防城港', 59635, 21.6667, ..., 20, 5.0, 26.4],
        ['防城港', 59635, 21.6667, ..., 354, 7.7, 31.1],
        ['防城港', 59635, 21.6667, ..., 28, 7.3, 29.6],
        ...,
        ['防城港', 59635, 21.6667, ..., 110, 2.0, 22.6],
        ['防城港', 59635, 21.6667, ..., 62, 0.5, 22.5],
        ['防城港', 59635, 21.6667, ..., 68, 0.8, 22.6]], dtype=object),
 array([['涠洲岛', 59647, 21.0333, ..., 77, 4.5, 28.8],
        ['涠洲岛', 59647, 21.0333, ..., 309, 4.4, 31.0],
        ['涠洲岛', 59647, 21.0333, ..., 241, 2.6, 33.0],
        ...,
        ['涠洲岛', 59647, 21.0333, ..., 74, 2.4, 23.4],
        ['涠洲岛', 59647, 21.0333, ..., 74, 4.3, 23.1],
        ['涠洲岛', 59647, 21.0333, ..., 94, 3.5, 23.1]], dtype=object),
 array([['遂溪', 59650, 21.4036, ..., 75, 3.8, 27.8],
        ['遂溪', 59650, 21.4036, ..., 105, 4.5, 30.1],
        ['遂溪', 59650, 21.4036, ..., 80, 4.7, 31.8],
        ...,
        ['遂溪', 59650, 21.4036, ..., 26, 1.1, 22.3],
        ['遂溪', 59650, 21.4036, ..., 23, 1.0, 21.5],
        ['遂溪', 59650, 21.4036, ..., 115, 2.5, 21.5]], dtype=object),
 array([['高州', 59653, 21.9425, ..., 317, 0.5, 27.8],
        ['高州', 59653, 21.9425, ..., 19, 1.5, 33.0],
        ['高州', 59653, 21.9425, ..., 52, 1.7, 35.4],
        ...,
        ['高州', 59653, 21.9425, ..., 309, 1.1, 20.1],
        ['高州', 59653, 21.9425, ..., 84, 1.0, 20.4],
        ['高州', 59653, 21.9425, ..., 0, 0.0, 20.2]], dtype=object),
 array([['廉江', 59654, 21.6331, ..., 56, 2.8, 27.5],
        ['廉江', 59654, 21.6331, ..., 65, 4.4, 34.1],
        ['廉江', 59654, 21.6331, ..., 42, 2.0, 35.8],
        ...,
        ['廉江', 59654, 21.6331, ..., 0, 0.0, 22.0],
        ['廉江', 59654, 21.6331, ..., 58, 1.1, 20.8],
        ['廉江', 59654, 21.6331, ..., 37, 0.8, 20.9]], dtype=object),
 array([['化州', 59655, 21.6472, ..., 25, 1.4, 27.3],
        ['化州', 59655, 21.6472, ..., 41, 0.8, 32.7],
        ['化州', 59655, 21.6472, ..., 99, 1.0, 32.4],
        ...,
        ['化州', 59655, 21.6472, ..., 0, 0.0, 22.4],
        ['化州', 59655, 21.6472, ..., 233, 0.9, 22.1],
        ['化州', 59655, 21.6472, ..., 133, 0.7, 21.6]], dtype=object),
 array([['吴川', 59656, 21.4058, ..., 46, 2.0, 27.1],
        ['吴川', 59656, 21.4058, ..., 63, 2.9, 28.9],
        ['吴川', 59656, 21.4058, ..., 89, 4.6, 31.2],
        ...,
        ['吴川', 59656, 21.4058, ..., 43, 1.6, 21.7],
        ['吴川', 59656, 21.4058, ..., 28, 1.4, 21.1],
        ['吴川', 59656, 21.4058, ..., 61, 1.5, 21.3]], dtype=object),
 array([['湛江市特呈岛', 59657, 21.1494, ..., 42, 4.2, 0.0],
        ['湛江市特呈岛', 59657, 21.1494, ..., 49, 3.4, 0.0],
        ['湛江市特呈岛', 59657, 21.1494, ..., 84, 4.1, 0.0],
        ...,
        ['湛江市特呈岛', 59657, 21.1603, ..., 81, 2.9, 0.0],
        ['湛江市特呈岛', 59657, 21.1603, ..., 15, 1.5, 0.0],
        ['湛江市特呈岛', 59657, 21.1517, ..., 51, 3.8, 0.0]], dtype=object),
 array([['湛江', 59658, 21.1547, ..., 72, 2.7, 27.2],
        ['湛江', 59658, 21.1547, ..., 60, 4.7, 30.7],
        ['湛江', 59658, 21.1547, ..., 96, 5.8, 32.8],
        ...,
        ['湛江', 59658, 21.1547, ..., 89, 1.4, 22.2],
        ['湛江', 59658, 21.1547, ..., 38, 1.8, 21.2],
        ['湛江', 59658, 21.1547, ..., 49, 2.1, 21.6]], dtype=object),
 array([['电白', 59664, 21.5458, ..., 50, 2.1, 27.6],
        ['电白', 59664, 21.5458, ..., 54, 3.4, 30.2],
        ['电白', 59664, 21.5458, ..., 54, 2.2, 33.0],
        ...,
        ['电白', 59664, 21.5458, ..., 56, 1.4, 20.7],
        ['电白', 59664, 21.5458, ..., 69, 1.3, 20.2],
        ['电白', 59664, 21.5458, ..., 52, 1.4, 20.6]], dtype=object),
 array([['上川岛', 59673, 21.7358, ..., 220, 0.4, 24.9],
        ['上川岛', 59673, 21.7358, ..., 71, 6.2, 25.4],
        ['上川岛', 59673, 21.7358, ..., 52, 6.8, 25.3],
        ...,
        ['上川岛', 59673, 21.7358, ..., 37, 2.5, 20.0],
        ['上川岛', 59673, 21.7358, ..., 33, 2.5, 20.3],
        ['上川岛', 59673, 21.7358, ..., 46, 2.8, 20.7]], dtype=object),
 array([['雷州', 59750, 20.9619, ..., 76, 4.4, 27.7],
        ['雷州', 59750, 20.9619, ..., 78, 3.1, 30.6],
        ['雷州', 59750, 20.9619, ..., 94, 4.4, 33.5],
        ...,
        ['雷州', 59750, 20.9619, ..., 90, 2.1, 22.1],
        ['雷州', 59750, 20.9619, ..., 100, 1.4, 22.2],
        ['雷州', 59750, 20.9619, ..., 97, 1.9, 22.2]], dtype=object),
 array([['徐闻', 59754, 20.2428, ..., 358, 1.2, 28.0],
        ['徐闻', 59754, 20.2428, ..., 101, 1.2, 29.6],
        ['徐闻', 59754, 20.2428, ..., 95, 2.4, 26.7],
        ...,
        ['徐闻', 59754, 20.2428, ..., 56, 2.9, 20.2],
        ['徐闻', 59754, 20.2428, ..., 65, 2.9, 20.3],
        ['徐闻', 59754, 20.2428, ..., 88, 2.5, 20.6]], dtype=object),
 array([['徐闻县新寮岛', 59755, 20.6542, ..., 70, 7.9, 0.0],
        ['徐闻县新寮岛', 59755, 20.6542, ..., 74, 8.6, 0.0],
        ['徐闻县新寮岛', 59755, 20.6542, ..., 76, 6.3, 0.0],
        ...,
        ['徐闻县新寮岛', 59755, 20.6542, ..., 62, 3.5, 0.0],
        ['徐闻县新寮岛', 59755, 20.6542, ..., 74, 5.7, 0.0],
        ['徐闻县新寮岛', 59755, 20.6542, ..., 80, 5.0, 0.0]], dtype=object),
 array([['琼山', 59757, 20.0, ..., 0, 0.2, 29.7],
        ['琼山', 59757, 20.0, ..., 57, 1.5, 32.3],
        ['琼山', 59757, 20.0, ..., 101, 1.6, 36.2],
        ...,
        ['琼山', 59757, 20.0, ..., 36, 0.7, 20.9],
        ['琼山', 59757, 20.0, ..., 78, 0.8, 21.0],
        ['琼山', 59757, 20.0, ..., 78, 3.1, 21.2]], dtype=object),
 array([['海口', 59758, 20.0, ..., 73, 2.1, 35.5],
        ['海口', 59758, 20.0, ..., 128, 3.3, 36.6],
        ['海口', 59758, 20.0, ..., 37, 3.6, 44.6],
        ...,
        ['海口', 59758, 20.0, ..., 77, 1.4, 20.0],
        ['海口', 59758, 20.0, ..., 74, 2.1, 19.9],
        ['海口', 59758, 20.0, ..., 88, 2.7, 20.0]], dtype=object),
 array([['洋浦', 59840, 19.7736, ..., 97, 0.6, 27.2],
        ['洋浦', 59840, 19.7736, ..., 98, 2.3, 29.3],
        ['洋浦', 59840, 19.7736, ..., 144, 3.0, 32.2],
        ...,
        ['洋浦', 59840, 19.7736, ..., 116, 0.6, 22.0],
        ['洋浦', 59840, 19.7736, ..., 89, 1.3, 21.4],
        ['洋浦', 59840, 19.7736, ..., 68, 1.2, 21.2]], dtype=object),
 array([['临高', 59842, 19.9, ..., 94, 1.9, 29.7],
        ['临高', 59842, 19.9, ..., 104, 2.1, 33.3],
        ['临高', 59842, 19.9, ..., 123, 1.9, 37.8],
        ...,
        ['临高', 59842, 19.9, ..., 157, 0.3, 21.2],
        ['临高', 59842, 19.9, ..., 0, 0.2, 21.3],
        ['临高', 59842, 19.9, ..., 85, 0.5, 21.5]], dtype=object),
 array([['澄迈', 59843, 19.7369, ..., 33, 0.9, 26.9],
        ['澄迈', 59843, 19.7369, ..., 63, 1.2, 32.4],
        ['澄迈', 59843, 19.7369, ..., 113, 1.4, 37.4],
        ...,
        ['澄迈', 59843, 19.7369, ..., 0, 0.0, 19.7],
        ['澄迈', 59843, 19.7369, ..., 0, 0.0, 19.5],
        ['澄迈', 59843, 19.7369, ..., 48, 1.3, 19.3]], dtype=object),
 array([['儋州', 59845, 19.5167, ..., 140, 1.3, 27.1],
        ['儋州', 59845, 19.5167, ..., 88, 1.4, 31.4],
        ['儋州', 59845, 19.5167, ..., 123, 2.8, 35.2],
        ...,
        ['儋州', 59845, 19.5167, ..., 62, 0.8, 20.0],
        ['儋州', 59845, 19.5167, ..., 97, 0.8, 19.9],
        ['儋州', 59845, 19.5167, ..., 112, 1.2, 19.9]], dtype=object),
 array([['昌江', 59847, 19.2667, ..., 111, 0.6, 26.1],
        ['昌江', 59847, 19.2667, ..., 112, 2.4, 30.8],
        ['昌江', 59847, 19.2667, ..., 146, 1.4, 37.1],
        ...,
        ['昌江', 59847, 19.2667, ..., 223, 1.6, 21.0],
        ['昌江', 59847, 19.2667, ..., 89, 2.0, 20.8],
        ['昌江', 59847, 19.2667, ..., 109, 2.7, 20.6]], dtype=object),
 array([['白沙', 59848, 19.2333, ..., 5, 0.3, 27.6],
        ['白沙', 59848, 19.2333, ..., 0, 0.0, 30.2],
        ['白沙', 59848, 19.2333, ..., 212, 1.4, 31.6],
        ...,
        ['白沙', 59848, 19.2333, ..., 0, 0.0, 22.3],
        ['白沙', 59848, 19.2333, ..., 0, 0.0, 22.0],
        ['白沙', 59848, 19.2333, ..., 232, 1.4, 22.2]], dtype=object),
 array([['琼中', 59849, 19.0353, ..., 0, 0.2, 29.5],
        ['琼中', 59849, 19.0353, ..., 69, 2.2, 31.7],
        ['琼中', 59849, 19.0353, ..., 48, 1.0, 33.8],
        ...,
        ['琼中', 59849, 19.0353, ..., 260, 2.7, 19.3],
        ['琼中', 59849, 19.0353, ..., 253, 2.0, 18.7],
        ['琼中', 59849, 19.0353, ..., 258, 3.0, 18.4]], dtype=object),
 array([['定安', 59851, 19.6672, ..., 0, 0.0, 28.7],
        ['定安', 59851, 19.6672, ..., 243, 0.9, 32.6],
        ['定安', 59851, 19.6672, ..., 80, 1.9, 38.7],
        ...,
        ['定安', 59851, 19.6672, ..., 316, 1.6, 19.7],
        ['定安', 59851, 19.6672, ..., 321, 1.0, 19.6],
        ['定安', 59851, 19.6672, ..., 334, 1.1, 19.8]], dtype=object),
 array([['翁田', 59852, 19.9928, ..., 48, 0.0, 0.0],
        ['翁田', 59852, 19.9928, ..., 75, 3.6, 0.0],
        ['翁田', 59852, 19.9928, ..., 87, 1.9, 0.0],
        ...,
        ['翁田', 59852, 19.9928, ..., 62, 1.9, 0.0],
        ['翁田', 59852, 19.9928, ..., 57, 2.6, 0.0],
        ['翁田', 59852, 19.9928, ..., 61, 2.1, 0.0]], dtype=object),
 array([['屯昌', 59854, 19.3667, ..., 225, 1.2, 26.8],
        ['屯昌', 59854, 19.3667, ..., 234, 0.5, 28.8],
        ['屯昌', 59854, 19.3667, ..., 196, 1.0, 34.7],
        ...,
        ['屯昌', 59854, 19.3667, ..., 295, 1.1, 20.0],
        ['屯昌', 59854, 19.3667, ..., 0, 0.0, 19.7],
        ['屯昌', 59854, 19.3667, ..., 0, 0.0, 19.8]], dtype=object),
 array([['琼海', 59855, 19.2089, ..., 295, 0.5, 27.9],
        ['琼海', 59855, 19.2089, ..., 266, 2.2, 29.4],
        ['琼海', 59855, 19.2089, ..., 301, 0.6, 38.6],
        ...,
        ['琼海', 59855, 19.2089, ..., 330, 3.8, 20.4],
        ['琼海', 59855, 19.2089, ..., 346, 2.3, 20.3],
        ['琼海', 59855, 19.2089, ..., 342, 3.2, 20.5]], dtype=object),
 array([['文昌', 59856, 19.6167, ..., 325, 1.5, 30.5],
        ['文昌', 59856, 19.6167, ..., 0, 0.0, 35.3],
        ['文昌', 59856, 19.6167, ..., 0, 0.0, 34.7],
        ...,
        ['文昌', 59856, 19.6167, ..., 322, 1.6, 19.7],
        ['文昌', 59856, 19.6167, ..., 307, 1.2, 19.5],
        ['文昌', 59856, 19.6167, ..., 292, 0.8, 19.6]], dtype=object),
 array([['莺歌海', 59936, 18.5297, ..., 56, 0.1, 0.0],
        ['莺歌海', 59936, 18.5297, ..., 175, 0.4, 0.0],
        ['莺歌海', 59936, 18.5297, ..., 112, 2.2, 0.0],
        ...,
        ['莺歌海', 59936, 18.5297, ..., 59, 1.2, 0.0],
        ['莺歌海', 59936, 18.5297, ..., 55, 1.3, 0.0],
        ['莺歌海', 59936, 18.5297, ..., 82, 0.8, 0.0]], dtype=object),
 array([['乐东', 59940, 18.7494, ..., 25, 1.8, 27.3],
        ['乐东', 59940, 18.7494, ..., 104, 1.7, 29.0],
        ['乐东', 59940, 18.7494, ..., 339, 2.3, 32.8],
        ...,
        ['乐东', 59940, 18.7494, ..., 338, 0.9, 20.3],
        ['乐东', 59940, 18.7494, ..., 13, 2.7, 20.1],
        ['乐东', 59940, 18.7494, ..., 21, 2.7, 20.0]], dtype=object),
 array([['五指山', 59941, 18.7667, ..., 92, 0.9, 24.7],
        ['五指山', 59941, 18.7667, ..., 61, 0.6, 27.4],
        ['五指山', 59941, 18.7667, ..., 68, 1.9, 34.8],
        ...,
        ['五指山', 59941, 18.7667, ..., 0, 0.2, 20.1],
        ['五指山', 59941, 18.7667, ..., 256, 1.3, 19.5],
        ['五指山', 59941, 18.7667, ..., 274, 1.6, 19.0]], dtype=object),
 array([['保亭', 59945, 18.65, ..., 0, 0.0, 26.1],
        ['保亭', 59945, 18.65, ..., 245, 1.3, 30.3],
        ['保亭', 59945, 18.65, ..., 172, 0.5, 36.5],
        ...,
        ['保亭', 59945, 18.65, ..., 55, 3.5, 20.7],
        ['保亭', 59945, 18.65, ..., 0, 0.0, 20.2],
        ['保亭', 59945, 18.65, ..., 33, 1.7, 20.2]], dtype=object),
 array([['三亚', 59948, 18.2244, ..., 70, 4.7, 24.6],
        ['三亚', 59948, 18.2244, ..., 86, 4.3, 27.2],
        ['三亚', 59948, 18.2244, ..., 61, 4.8, 27.4],
        ...,
        ['三亚', 59948, 18.2244, ..., 40, 12.4, 18.9],
        ['三亚', 59948, 18.2244, ..., 37, 11.1, 18.7],
        ['三亚', 59948, 18.2244, ..., 40, 11.9, 18.9]], dtype=object),
 array([['万宁', 59951, 18.8, ..., 0, 0.1, 28.5],
        ['万宁', 59951, 18.8, ..., 18, 1.5, 31.4],
        ['万宁', 59951, 18.8, ..., 4, 2.6, 34.3],
        ...,
        ['万宁', 59951, 18.8, ..., 332, 2.5, 21.1],
        ['万宁', 59951, 18.8, ..., 350, 3.8, 20.7],
        ['万宁', 59951, 18.8, ..., 345, 3.4, 20.6]], dtype=object),
 array([['陵水', 59954, 18.55, ..., 332, 0.7, 27.9],
        ['陵水', 59954, 18.55, ..., 0, 0.0, 29.9],
        ['陵水', 59954, 18.55, ..., 0, 0.0, 32.3],
        ...,
        ['陵水', 59954, 18.55, ..., 25, 2.5, 21.9],
        ['陵水', 59954, 18.55, ..., 16, 7.1, 21.5],
        ['陵水', 59954, 18.55, ..., 20, 7.8, 21.4]], dtype=object)]

In [36]:
data = np.load('./data_10.npy',allow_pickle=True)
# S, _, D = data.shape
route = []
for k in range(len(data)):
    dt = pd.DataFrame(data[k])
    
    # data.shape
    for i in range(len(data)):
        dt[1][i] = str(dt[5][i])+'-'+str(dt[6][i])+'-'+str(dt[7][i])+'-'+str(dt[8][i])
    dt.drop([0,1,5,6,7,8],axis=1,inplace=True)
    pl  = dt.mean().tolist()
    route.append(pl)

data
# plt.plot(range(len(rain_drop)),rain_drop)

array([[['河口', '2020-10-1-0', 22.5, ..., 346, 0.6, 26.2],
        ['河口', '2020-10-1-1', 22.5, ..., 152, 0.7, 26.4],
        ['河口', '2020-10-1-2', 22.5, ..., 6, 0.4, 27.0],
        ...,
        ['河口', 56989, 22.5, ..., 0, 0.0, 22.4],
        ['河口', 56989, 22.5, ..., 0, 0.0, 22.3],
        ['河口', 56989, 22.5, ..., 0, 0.0, 22.1]],

       [['万盛', '2020-10-1-0', 28.9894, ..., 37, 1.3, 18.7],
        ['万盛', '2020-10-1-1', 28.9894, ..., 8, 2.0, 19.7],
        ['万盛', '2020-10-1-2', 28.9894, ..., 20, 2.2, 20.1],
        ...,
        ['万盛', 57509, 28.9894, ..., 23, 1.0, 14.7],
        ['万盛', 57509, 28.9894, ..., 93, 0.4, 14.7],
        ['万盛', 57509, 28.9894, ..., 357, 1.1, 14.5]],

       [['长寿', '2020-10-1-0', 29.8333, ..., 14, 2.1, 21.1],
        ['长寿', '2020-10-1-1', 29.8333, ..., 360, 2.3, 21.7],
        ['长寿', '2020-10-1-2', 29.8333, ..., 354, 0.8, 22.1],
        ...,
        ['长寿', 57520, 29.8333, ..., 233, 2.8, 15.5],
        ['长寿', 57520, 29.8333, ..., 259, 2.1, 15.4],
        ['长寿', 57520, 29.8333, ..., 236, 2.9, 15.4]],

       ...,

       [['三亚', '2020-10-1-0', 18.2244, ..., 70, 4.7, 24.6],
        ['三亚', '2020-10-1-1', 18.2244, ..., 86, 4.3, 27.2],
        ['三亚', '2020-10-1-2', 18.2244, ..., 61, 4.8, 27.4],
        ...,
        ['三亚', 59948, 18.2244, ..., 40, 12.4, 18.9],
        ['三亚', 59948, 18.2244, ..., 37, 11.1, 18.7],
        ['三亚', 59948, 18.2244, ..., 40, 11.9, 18.9]],

       [['万宁', '2020-10-1-0', 18.8, ..., 0, 0.1, 28.5],
        ['万宁', '2020-10-1-1', 18.8, ..., 18, 1.5, 31.4],
        ['万宁', '2020-10-1-2', 18.8, ..., 4, 2.6, 34.3],
        ...,
        ['万宁', 59951, 18.8, ..., 332, 2.5, 21.1],
        ['万宁', 59951, 18.8, ..., 350, 3.8, 20.7],
        ['万宁', 59951, 18.8, ..., 345, 3.4, 20.6]],

       [['陵水', '2020-10-1-0', 18.55, ..., 332, 0.7, 27.9],
        ['陵水', '2020-10-1-1', 18.55, ..., 0, 0.0, 29.9],
        ['陵水', '2020-10-1-2', 18.55, ..., 0, 0.0, 32.3],
        ...,
        ['陵水', 59954, 18.55, ..., 25, 2.5, 21.9],
        ['陵水', 59954, 18.55, ..., 16, 7.1, 21.5],
        ['陵水', 59954, 18.55, ..., 20, 7.8, 21.4]]], dtype=object)

In [37]:
from datetime import datetime, timedelta

data = np.load('./data_10.npy',allow_pickle=True)

aps = datetime(data[0][0][5],data[0][0][6],data[0][0][7],data[0][0][8])
tje = []
for i in range(744):
    tje.append((aps+timedelta(hours=i)).strftime("%Y-%m-%d-%H"))

data_new = []
for i in range(len(data)):
    dt = pd.DataFrame(data[i])
    dt[1] = tje
    dt.drop([0,5,6,7,8],axis=1,inplace=True)
    data_new.append(dt.to_numpy())

data = np.array(data_new)

data = data[:,:,[0,7,3,4,5,6]]
data[:,:,1] = 10
np.save('./evaluate.npy',data)
data

array([[['2020-10-01-00', 10, 137.8, 25.3, 25.3, 100],
        ['2020-10-01-01', 10, 137.8, 25.6, 25.6, 100],
        ['2020-10-01-02', 10, 137.8, 25.8, 25.8, 100],
        ...,
        ['2020-10-31-21', 10, 137.8, 22.1, 21.4, 96],
        ['2020-10-31-22', 10, 137.8, 22.1, 21.4, 96],
        ['2020-10-31-23', 10, 137.8, 21.9, 21.4, 97]],

       [['2020-10-01-00', 10, 599.8, 19.2, 16.6, 85],
        ['2020-10-01-01', 10, 599.8, 18.8, 17.3, 91],
        ['2020-10-01-02', 10, 599.8, 19.3, 17.1, 87],
        ...,
        ['2020-10-31-21', 10, 599.8, 14.3, 13.8, 97],
        ['2020-10-31-22', 10, 599.8, 14.2, 13.7, 97],
        ['2020-10-31-23', 10, 599.8, 14.0, 13.5, 97]],

       [['2020-10-01-00', 10, 377.6, 21.1, 18.7, 86],
        ['2020-10-01-01', 10, 377.6, 21.3, 18.9, 86],
        ['2020-10-01-02', 10, 377.6, 21.6, 19.0, 85],
        ...,
        ['2020-10-31-21', 10, 377.6, 15.2, 14.9, 98],
        ['2020-10-31-22', 10, 377.6, 15.1, 14.9, 99],
        ['2020-10-31-23', 10, 377.6, 15.1, 14.9, 99]],

       ...,

       [['2020-10-01-00', 10, 419.4, 24.7, 23.8, 95],
        ['2020-10-01-01', 10, 419.4, 25.3, 24.4, 95],
        ['2020-10-01-02', 10, 419.4, 25.4, 24.2, 93],
        ...,
        ['2020-10-31-21', 10, 419.4, 20.6, 17.8, 84],
        ['2020-10-31-22', 10, 419.4, 20.3, 17.9, 86],
        ['2020-10-31-23', 10, 419.4, 20.4, 17.6, 84]],

       [['2020-10-01-00', 10, 39.9, 26.0, 25.5, 97],
        ['2020-10-01-01', 10, 39.9, 27.9, 25.5, 87],
        ['2020-10-01-02', 10, 39.9, 29.4, 25.6, 80],
        ...,
        ['2020-10-31-21', 10, 39.9, 22.0, 19.9, 88],
        ['2020-10-31-22', 10, 39.9, 21.7, 19.3, 86],
        ['2020-10-31-23', 10, 39.9, 21.8, 19.0, 84]],

       [['2020-10-01-00', 10, 35.2, 26.4, 24.1, 87],
        ['2020-10-01-01', 10, 35.2, 27.7, 24.3, 82],
        ['2020-10-01-02', 10, 35.2, 29.1, 24.7, 77],
        ...,
        ['2020-10-31-21', 10, 35.2, 22.7, 19.5, 82],
        ['2020-10-31-22', 10, 35.2, 22.7, 18.3, 76],
        ['2020-10-31-23', 10, 35.2, 23.0, 18.1, 74]]], dtype=object)

In [38]:
route = np.array(route)
route = pd.DataFrame(route)
route

,0,1,2,3,4,5,6,7,8
0,22.500000,103.950000,137.800000,23.997446,21.568145,88.254032,153.431452,1.443145,26.034946
1,28.989400,106.918600,599.800000,15.748387,13.894355,89.534946,151.799731,1.585887,17.116935
2,29.833300,107.066700,377.600000,16.869489,15.033737,89.572581,129.748656,1.582796,17.678898
3,29.516700,108.766700,786.900000,14.053629,12.013978,88.427419,113.272849,1.732527,15.479301
4,29.684400,109.143600,776.900000,13.884140,11.960349,89.319892,112.840054,1.523387,15.347043
5,29.998600,109.475300,571.800000,14.872446,13.275672,91.024194,161.870968,0.995565,16.629570
6,29.883900,110.025300,539.800000,15.550134,12.955645,85.669355,162.267473,0.840726,17.571909
7,23.600000,107.116700,111.200000,22.114113,17.767473,78.206989,207.688172,2.216263,23.503629
8,22.066700,106.733300,348.700000,20.770161,17.403091,82.638441,147.595430,1.663978,22.007392
9,22.116700,107.033300,168.400000,21.692473,18.428495,83.620968,115.513441,2.765860,22.571774
10,22.183300,108.016700,216.000000,21.166129,17.913038,83.026882,112.575269,2.828091,22.737634
11,21.566700,107.950000,56.800000,24.301882,18.850269,73.604839,149.330645,4.918280,26.622849
12,21.783300,108.350000,32.400000,23.439919,18.091532,73.924731,98.629032,5.820296,24.846640
13,21.666706,108.399760,49.300000,23.201344,18.183602,74.930108,109.694892,8.192876,24.686962
14,21.033300,109.100000,55.200000,24.494355,19.910215,76.473118,139.375000,6.908737,27.345565
15,21.403600,110.244400,29.700000,24.365323,19.976882,78.131720,91.081989,3.895027,26.592204
16,21.942500,110.859200,77.000000,24.339785,19.390188,75.469086,209.254032,4.014785,25.482661
17,21.633100,110.303300,29.300000,24.589382,19.763844,75.986559,145.227151,3.769355,26.547715
18,21.647200,110.614400,31.900000,25.084677,19.886962,74.447581,161.823925,2.772043,27.546505
19,21.405800,110.810000,27.300000,24.669758,20.549059,79.059140,115.452957,4.005780,27.093280
20,21.150251,110.440070,7.712366,25.626075,14.613172,79.947581,70.581989,3.990591,0.000000
21,21.154700,110.302200,53.400000,24.490995,20.203360,78.204301,107.727151,4.996371,27.036694
22,21.545800,110.988600,31.800000,24.789651,19.606720,74.614247,84.801075,4.089516,26.765860
23,21.735800,112.773100,21.900000,24.712500,19.827285,75.145161,67.962366,8.768683,26.214651
24,20.961900,110.067800,33.600000,24.501075,20.799462,81.077957,112.537634,4.334409,26.643280
25,20.242800,110.165000,11.400000,25.421640,21.415726,79.420699,94.638441,6.403898,27.231048
26,20.654934,110.444658,12.334140,25.547312,20.154704,78.547043,87.079301,8.141935,0.000000
27,20.000000,110.366700,9.900000,25.822581,22.056452,80.544355,99.288978,3.985349,25.837634
28,20.000000,110.250000,63.500000,25.223387,21.490188,80.518817,83.006720,5.999194,25.160349
29,19.773600,109.204200,49.000000,24.784946,21.875134,84.250000,67.556452,4.083199,25.194489
30,19.900000,109.683300,31.700000,25.065457,21.770296,82.698925,86.842742,4.914382,25.920565
31,19.736900,110.016400,31.400000,25.043817,22.127419,84.586022,81.623656,3.581048,26.396237
32,19.516700,109.583300,169.000000,24.266129,21.414516,84.860215,98.654570,3.171909,25.179704
33,19.266700,109.050000,98.100000,25.287634,21.173925,78.768817,105.708333,3.443414,26.691801
34,19.233300,109.433300,215.600000,23.622043,21.631048,89.333333,106.342742,2.168145,25.405242
35,19.035300,109.841900,300.800000,23.154032,21.249731,89.704301,142.740591,3.713575,23.893011
36,19.667200,110.337800,53.300000,25.007796,22.461559,86.375000,97.825269,4.893952,25.925134
37,19.992800,110.931100,33.000000,25.653360,22.146237,81.619624,74.693548,3.981720,0.000000
38,19.366700,110.100000,118.300000,24.698387,21.843145,84.779570,117.497312,3.134140,25.363844
39,19.208900,110.481900,23.300000,25.520027,22.509946,84.094086,131.205645,5.502419,26.179839
40,19.616700,110.750000,21.700000,25.715860,22.415860,82.567204,85.294355,3.719489,25.992204
41,18.529700,108.768900,15.000000,25.895968,22.188172,81.076613,191.954301,1.594624,0.000000
42,18.749400,109.163900,155.000000,25.181720,21.508737,81.053763,112.102151,3.264247,26.511022
43,18.766700,109.516700,328.500000,24.215995,20.761962,81.998656,166.620968,2.384946,25.577688
44,18.650000,109.700000,68.600000,25.759140,21.938978,80.729839,121.596774,2.722446,26.662097
45,18.224400,109.589700,419.400000,23.182258,21.399194,90.235215,85.092742,11.130108,24.093280
46,18.800000,110.333300,39.900000,25.269086,22.722849,86.473118,167.556452,5.134005,25.725134
47,18.550000,110.033300,35.200000,25.794220,22.078629,80.696237,90.935484,5.979167,25.963710

In [39]:
def find_correlation(data: pd.DataFrame):
    corr = data.corr(method='pearson')
    fig, ax = plt.subplots(figsize=(10, 10))
    ax.set_title('Pearson correlation')
    sns.heatmap(corr, annot=True, fmt='.2f', cmap='Blues')
    plt.show()
for i in range(540,549):
    als  =pd.DataFrame(data[i])
    als.drop([0,1],axis=1,inplace=True)
    find_correlation(als)

IndexError: index 540 is out of bounds for axis 0 with size 48